name: Simple Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install llvm

      - name: Build the project without -fuse-ld=lld
        run: |
          make WIN_LDFLAGS="$(echo "$(make WIN_LDFLAGS)" | sed 's/-fuse-ld=lld//g')"
