name: Simple Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install llvm

      - name: Adjust Makefile for Windows build
        run: |
          sed -i '' 's/-fuse-ld=lld//g' Makefile

      - name: Build the project
        run: |
          make