name: Simple Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM (includes lld)
        run: brew install llvm

      - name: Add LLVM to PATH
        run: echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

      - name: Build the project
        run: make
